# -*- coding: utf-8 -*-
"""
Created on Thu Dec  7 11:25:03 2023

@author: shangfr
"""
sdxl_styles = {
    'styles': [{'Style': '3D Model',
                'Prompt': 'professional 3d model {} . octane render, highly detailed, volumetric, dramatic lighting',
                'Negative prompt': 'ugly, deformed, noisy, low poly, blurry, painting'},
               {'Style': 'Analog Film',
                'Prompt': 'analog film photo {} . faded film, desaturated, 35mm photo, grainy, vignette, vintage, Kodachrome, Lomography, stained, highly detailed, found footage',
                'Negative prompt': 'painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured'},
               {'Style': 'Anime',
                'Prompt': 'anime artwork {} . anime style, key visual, vibrant, studio anime, highly detailed',
                'Negative prompt': 'photo, deformed, black and white, realism, disfigured, low contrast'},
               {'Style': 'Cinematic',
                'Prompt': 'cinematic film still {} . shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy',
                'Negative prompt': 'anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured'},
               {'Style': 'Comic Book',
                'Prompt': 'comic {} . graphic illustration, comic art, graphic novel art, vibrant, highly detailed',
                'Negative prompt': 'photograph, deformed, glitch, noisy, realistic, stock photo'},
               {'Style': 'Craft Clay',
                'Prompt': 'play-doh style {} . sculpture, clay art, centered composition, Claymation',
                'Negative prompt': 'sloppy, messy, grainy, highly detailed, ultra textured, photo'},
               {'Style': 'Digital Art',
                'Prompt': 'concept art {} . digital artwork, illustrative, painterly, matte painting, highly detailed',
                'Negative prompt': 'photo, photorealistic, realism, ugly'},
               {'Style': 'Enhance',
                'Prompt': 'breathtaking {} . award-winning, professional, highly detailed',
                'Negative prompt': 'ugly, deformed, noisy, blurry, distorted, grainy'},
               {'Style': 'Fantasy Art',
                'Prompt': 'ethereal fantasy concept art of {} . magnificent, celestial, ethereal, painterly, epic, majestic, magical, fantasy art, cover art, dreamy',
                'Negative prompt': 'photographic, realistic, realism, 35mm film, dslr, cropped, frame, text, deformed, glitch, noise, noisy, off-center, deformed, cross-eyed, closed eyes, bad anatomy, ugly, disfigured, sloppy, duplicate, mutated, black and white'},
               {'Style': 'Isometric',
                'Prompt': 'isometric style {} . vibrant, beautiful, crisp, detailed, ultra detailed, intricate',
                'Negative prompt': 'deformed, mutated, ugly, disfigured, blur, blurry, noise, noisy, realistic, photographic'},
               {'Style': 'Line Art',
                'Prompt': 'line art drawing {} . professional, sleek, modern, minimalist, graphic, line art, vector graphics',
                'Negative prompt': 'anime, photorealistic, 35mm film, deformed, glitch, blurry, noisy, off-center, deformed, cross-eyed, closed eyes, bad anatomy, ugly, disfigured, mutated, realism, realistic, impressionism, expressionism, oil, acrylic'},
               {'Style': 'Lowpoly',
                'Prompt': 'low-poly style {} . low-poly game art, polygon mesh, jagged, blocky, wireframe edges, centered composition',
                'Negative prompt': 'noisy, sloppy, messy, grainy, highly detailed, ultra textured, photo'},
               {'Style': 'Neonpunk',
                'Prompt': 'neonpunk style {} . cyberpunk, vaporwave, neon, vibes, vibrant, stunningly beautiful, crisp, detailed, sleek, ultramodern, magenta highlights, dark purple shadows, high contrast, cinematic, ultra detailed, intricate, professional',
                'Negative prompt': 'painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured'},
               {'Style': 'Origami',
                'Prompt': 'origami style {} . paper art, pleated paper, folded, origami art, pleats, cut and fold, centered composition',
                'Negative prompt': 'noisy, sloppy, messy, grainy, highly detailed, ultra textured, photo'},
               {'Style': 'Photographic',
                'Prompt': 'cinematic photo {} . 35mm photograph, film, bokeh, professional, 4k, highly detailed',
                'Negative prompt': 'drawing, painting, crayon, sketch, graphite, impressionist, noisy, blurry, soft, deformed, ugly'},
               {'Style': 'Pixel Art',
                'Prompt': 'pixel-art {} . low-res, blocky, pixel art style, 8-bit graphics',
                'Negative prompt': 'sloppy, messy, blurry, noisy, highly detailed, ultra textured, photo, realistic'},
               {'Style': 'Texture',
                'Prompt': 'texture {} top down close-up',
                'Negative prompt': 'ugly, deformed, noisy, blurry'}],
    'styles_cn': [{'Style': '3D模型',
                   'Prompt': '专业的3D模型 {}。用Octane渲染，高度详细，体积感强，戏剧性光影',
                   'Negative prompt': '丑陋，畸形，嘈杂，低多边形，模糊，绘画'},
                  {'Style': '模拟胶片',
                   'Prompt': '模拟胶片照片 {}。褪色的胶片，去饱和，35毫米照片，颗粒感，暗角，复古，柯达彩色胶片风格，Lomography，沾污，高度详细，发现的素材',
                   'Negative prompt': '绘画，绘图，插画，故障，畸形，变异，斜视，丑陋，畸形'},
                  {'Style': '动漫',
                   'Prompt': '动漫艺术作品 {}。动漫风格，关键视觉，生动，工作室动漫，高度详细',
                   'Negative prompt': '照片，畸形，黑白，现实主义，畸形，低对比度'},
                  {'Style': '电影',
                   'Prompt': '电影静止画 {}。景深浅，暗角，高度详细，高预算，虚化背景，宽银幕比例，情绪化，史诗般，华丽，电影颗粒感，颗粒状',
                   'Negative prompt': '动漫，卡通，图形，文字，绘画，蜡笔，石墨，抽象，故障，畸形'},
                  {'Style': '漫画书',
                   'Prompt': '漫画 {}。图形插图，漫画艺术，图像小说艺术，生动，高度详细',
                   'Negative prompt': '照片，畸形，故障，嘈杂，逼真，素材照片'},
                  {'Style': '手工粘土',
                   'Prompt': '橡皮泥风格 {}。雕塑，粘土艺术，中心构图，粘土动画',
                   'Negative prompt': '邋遢，混乱，颗粒感，高度详细，超级贴图，照片'},
                  {'Style': '数码艺术',
                   'Prompt': '概念艺术 {}。数码艺术作品，图解性，画家风格，哑光绘画，高度详细',
                   'Negative prompt': '照片，逼真照片，现实主义，丑陋'},
                  {'Style': '增强',
                   'Prompt': '令人叹为观止的 {}。屡获殊荣，专业，高度详细',
                   'Negative prompt': '丑陋，畸形，嘈杂，模糊，扭曲，颗粒状'},
                  {'Style': '奇幻艺术',
                   'Prompt': '关于 {}的超现实奇幻概念艺术。壮丽，天上的，超凡脱俗，画家风格，史诗般，雄伟，神奇，幻想艺术，封面艺术，梦幻',
                   'Negative prompt': '摄影的，现实主义，逼真，35毫米胶片，DSLR，裁剪，帧，文字，畸形，故障，嘈杂，嘈杂的，偏离中心，畸形，斜视，闭眼，解剖不正确，丑陋，畸形，邋遢，重复，变异，黑白'},
                  {'Style': '等距投影',
                   'Prompt': '等距投影风格 {}。生动，美丽，清晰，详细，超级详细，复杂',
                   'Negative prompt': '畸形，变异，丑陋，畸形，模糊，嘈杂，逼真，摄影'},
                  {'Style': '线条艺术',
                   'Prompt': '线条艺术绘图 {}。专业，时尚，现代，极简主义，图形，线条艺术，矢量图形',
                   'Negative prompt': '动漫，逼真照片，35毫米胶片，畸形，故障，模糊，嘈杂，偏离中心，畸形，斜视，闭眼，解剖不正确，丑陋，畸形，变异，现实主义，逼真，印象派，表现主义，油画，丙烯'},
                  {'Style': '低多边形',
                   'Prompt': '低多边形风格 {}。低多边形游戏艺术，多边形网格，锯齿状，方块状，线框边缘，中心构图',
                   'Negative prompt': '嘈杂，邋遢，混乱，颗粒感，高度详细，超级贴图，照片'},
                  {'Style': '霓虹朋克',
                   'Prompt': '霓虹朋克风格 {}。赛博朋克，蒸汽波，霓虹，氛围，生动，惊人的美丽，清晰，详细，时尚，超现代，品红色亮点，深紫色阴影，高对比度，电影化，超级详细，复杂，专业',
                   'Negative prompt': '绘画，绘图，插画，故障，畸形，变异，斜视，丑陋，畸形'},
                  {'Style': '折纸艺术',
                   'Prompt': '折纸风格 {}。纸艺术，褶皱的纸张，折叠，折纸艺术，褶皱，剪裁和折叠，中心构图',
                   'Negative prompt': '嘈杂，邋遢，混乱，颗粒感，高度详细，超级贴图，照片'},
                  {'Style': '摄影',
                   'Prompt': '电影式照片 {}。35毫米照片，胶片，虚化背景，专业，4K，高度详细',
                   'Negative prompt': '绘图，绘画，蜡笔，素描，石墨，印象派，嘈杂，模糊，柔和，畸形，丑陋'},
                  {'Style': '像素艺术',
                   'Prompt': '像素艺术 {}。低分辨率，方块状，像素艺术风格，8位图形',
                   'Negative prompt': '邋遢，混乱，模糊，嘈杂，高度详细，超级贴图，照片，逼真'},
                  {'Style': '纹理',
                   'Prompt': '纹理 {}上视近景',
                   'Negative prompt': '丑陋，畸形，嘈杂，模糊'}]}
